name: Release

on:
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
