name: Trigger Tests in nvim-java/tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger workflow in nvim-java/tests
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.INTEGRATION_TEST_TOKEN }}
        script: |
          github.rest.repos.createDispatchEvent({
            owner: 'nvim-java',
            repo: 'tests',
            event_type: 'test-nvim-java',
            client_payload: {
              triggered_by: context.repo.repo,
              ref: context.sha,
              event_type: context.eventName
            }
          });
