name: Trigger Tests in nvim-java/tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger-integration-tests:
    uses: nvim-java/tests/.github/workflows/test-nvim-java.yml@main
